repos:
# Terraform
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.77.2
  hooks:
    - id: terraform_fmt
      args:
        - --args=-diff
        - --args=-write=false
      exclude: ^.terraform/
    - id: terraform_tflint
      exclude: ^.terraform/
    - id: terraform_validate
      exclude: ^.terraform/
    - id: terraform_docs
      exclude: ^.terraform/
    - id: terraform_tfsec
      exclude: ^.terraform/
